os:
  - linux
  - windows
  - osx

dist: bionic
osx_image: xcode11.2

cache:
  timeout: 600
  cargo: false
  directories:
    - $HOME/build/opencv
    - $TRAVIS_BUILD_DIR/vcpkg

language: rust
rust:
  - stable
  - beta
#  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - os: linux
      env: OPENCV_VERSION=3.2.0 CARGO_FEATURES=opencv-32
      rust: stable

env:
  global:
    - Atlas_ROOT_DIR=/usr/include/ # for cmake to find lapacke.h
    - RUST_TOOLCHAIN=$TRAVIS_RUST_VERSION
    - OS_FAMILY=$TRAVIS_OS_NAME
  jobs:
    - OPENCV_VERSION=3.4.9 CHOCO_OPENCV_VERSION=3.4.8 OSX_OPENCV_VERSION=@3 CARGO_FEATURES=opencv-34
    - OPENCV_VERSION=4.2.0 CHOCO_OPENCV_VERSION=4.1.2 OSX_OPENCV_VERSION= CARGO_FEATURES=opencv-4

install:
  - ci/install.sh

script:
  - ci/script.sh
