[package]
name = "binding-generator"
version = "0.1.0"
authors = ["Pro <twisted.fall@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
clang = {version = "0.23", features = ["clang_6_0"]}
clang-sys = {version = "0.28", features = ["clang_6_0"]}
dunce = "1.0"
maplit = "1.0"
once_cell = "1.0"
percent-encoding = "2.0"
regex = "1.0"
